#!/bin/bash
echo "COMP340 - Assignment 4 Program\nThis program compiles 2 programs, executes them (executes the 2nd one first, then sleeps for 0.01 second which then executes program 1), then observes the outputs"

cp ./one.txt ./one.c
cp ./two.txt ./two.c

gcc -O3 -std=c11 one.c -o one
gcc -O3 -std=c11 two.c -o two

./two &
sleep 0.01
TWO_PID=$(pgrep two)

./one $TWO_PID

#"Prefix output statements in your programs with (PROCESS ONE) or (PROCESS TWO) accordingly"
#add code here

#Cleanup
#using -f is very dangerous however knowing that this program is run in its own folder, should be fine
rm -f one two one.c two.c